import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "./api/auth/AuthProvider";
import {ToastContainer} from "react-toastify";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`antialiased`}
        >
          <ToastContainer/>
          <Toaster position="top-right" richColors />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
